<a href="https://colab.research.google.com/github/kittanaiwisetkhro/BSC_DPDM2025/blob/main/Midterm_663020620_0_%E0%B8%99%E0%B8%B2%E0%B8%A2%E0%B8%81%E0%B8%A4%E0%B8%95%E0%B8%99%E0%B8%B1%E0%B8%A2_%E0%B8%A7%E0%B8%B4%E0%B9%80%E0%B8%A8%E0%B8%A9%E0%B8%84%E0%B8%A3%E0%B9%89%E0%B8%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Midterm**
---
นายกฤตนัย วิเศษคร้อ
663020620-0


---
**ไฟล์**
*   Output : https://drive.google.com/file/d/1AFquBHeQkg7zys2cXKBw4JDH_zRPaJ2x/view?usp=drive_link

*   อธิบายการใช้ AI : https://drive.google.com/file/d/1AFquBHeQkg7zys2cXKBw4JDH_zRPaJ2x/view?usp=drive_link

## ขั้นตอนที่ 0. นำเข้าข้อมูล

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
import pandas as pd
import numpy as np
import os
import glob
from datetime import datetime

### คำถามที่ 1. อ่านไฟล์ทั้งหมด แสดงโครงสร้างข้อมูล และอธิบายความหมายแต่ละคอลัมน์

#### อ่านไฟล์ทั้งหมด แสดงโครงสร้างข้อมูล

In [10]:
root_path = '/content/drive/MyDrive/BSC DPDM midterm 2025'

historical_path = os.path.join(root_path, 'Daily rain - (Statistics 2012-2024)', 'hii_daily_rain.csv')
stations_model_path = os.path.join(root_path, 'Input - (Operation Daily rain from API_ 2025)', 'Stations in the model_HII.csv')
input_2025_folder = os.path.join(root_path, 'Input - (Operation Daily rain from API_ 2025)')

In [81]:
df_history = pd.read_csv(historical_path)
df_history.head()

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily

In [16]:
df_model_stations = pd.read_csv(stations_model_path)
df_model_stations.head()

   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

In [ ]:
# เขียนฟังก์ชัน อ่านไฟล์ข้อมูลปี 2025 จากทุก Sub-folder ---
# ค้นหาไฟล์ .csv ทุกไฟล์ที่อยู่ใน folder ย่อย (2025-07 ถึง 2025-12)

In [57]:
def read_all_2025_rainfall_data(input_folder):
    all_files = []
    # Iterate through months 07 to 12
    for month_num in range(7, 13):
        month_str = f'2025-{month_num:02d}'
        month_folder = os.path.join(input_folder, month_str)

        # Check if the month folder exists
        if os.path.exists(month_folder):
            # Find all CSV files in the current month's folder
            csv_files = glob.glob(os.path.join(month_folder, '*.csv'))
            all_files.extend(csv_files)
        else:
            print(f"Warning: Folder {month_folder} not found. Skipping.")

    df_list = []
    for filename in all_files:
        try:
            df = pd.read_csv(filename)
            df_list.append(df)
        except Exception as e:
            print(f"Error reading {filename}: {e}")

    if df_list:
        combined_df = pd.concat(df_list, ignore_index=True)
        return combined_df
    else:
        print("No files found or read.")
        return pd.DataFrame()

# Call the function to read all 2025 rainfall data
df_2025 = read_all_2025_rainfall_data(input_2025_folder)


df_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180700 entries, 0 to 180699
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       176886 non-null  object
 1   rainfall_datetime_calc  176886 non-null  object
 2   rainfall_value          176882 non-null  float64
 3   tele_station_id         173072 non-null  float64
 4   tele_station_oldcode    168021 non-null  object
 5   measure_datetime        180700 non-null  object
 6   station_code            3814 non-null    object
 7   value                   3814 non-null    float64
dtypes: float64(3), object(5)
memory usage: 11.0+ MB

In [47]:
df_2025.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,station_code,value
0,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,435493.0,VLGE46,2025-07-20,NaN,NaN
1,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,265.0,BNLG,2025-07-20,NaN,NaN
2,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,4.4,549.0,DIWO,2025-07-20,NaN,NaN
3,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,539.0,CGKG,2025-07-20,NaN,NaN
4,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,901.0,PAT002,2025-07-20,NaN,NaN

#### อธิบายความหมายแต่ละคอลัมน์

In [77]:
print("\n--- df_history Info ---")
df_history.info()

print("\n--- df_model_stations Info ---")
df_model_stations.info()

print("\n--- df_2025 Info ---")
df_2025.info()

--- df_history Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3768463 entries, 0 to 3768462
Data columns (total 14 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  datetime64[ns, UTC+07:00]
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
 13  doy               int32
dtypes: datetime64[ns, UTC+07:00](1), float64(3), int32(1), object(9)
memory usage: 388.1+ MB

--- df_model_stations Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385 entries, 0 to 384
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    385 non-null    object
 1   Lat     385 non-null    float64
 2   Long    385 non-null    float64
dtypes: float64(2), object(1)
memory usage: 9.2+ KB

--- df_2025 Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180700 entries, 0 to 180699
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       176886 non-null  object
 1   rainfall_datetime_calc  176886 non-null  object
 2   rainfall_value          176882 non-null  float64
 3   tele_station_id         173072 non-null  float64
 4   tele_station_oldcode    168021 non-null  object
 5   measure_datetime        180700 non-null  object
 6   station_code            3814 non-null    object
 7   value                   3814 non-null    float64
dtypes: float64(3), object(5)
memory usage: 11.0+ MB

# Data Dictionary & Schema Definition

เอกสารนี้อธิบายโครงสร้างชุดข้อมูล (Dataframes) ที่ใช้ในโปรเจกต์ ทั้งข้อมูลสถิติย้อนหลัง, รายชื่อสถานีหลัก และข้อมูลดิบปีปัจจุบัน

---

## 1. `df_history` (Historical Data)
> **Description:** ข้อมูลสถิติน้ำฝนย้อนหลัง (ปี 2012-2024)
> **Purpose:** ใช้เป็นฐานข้อมูลอ้างอิง (Reference) เพื่อหาค่าเฉลี่ยหรือ Median สำหรับการ **Impute** เติมข้อมูลที่หายไป

| Column Name | Description | Note |
| :--- | :--- | :--- |
| **`station_code`** | รหัสสถานีโทรมาตร | 🔑 **Key หลัก** สำหรับอ้างอิงสถานี |
| `measure_datetime` | วันและเวลาที่ทำการตรวจวัด | Format: `YYYY-MM-DD HH:MM:SS` |
| **`data`** | ค่าปริมาณน้ำฝนที่วัดได้ (mm) | 🎯 ค่า Target ที่นำมาคำนวณสถิติ |
| `station_name` | ชื่อเรียกสถานี | ภาษาไทย/อังกฤษ |
| `latitude` | พิกัดละติจูด (เส้นรุ้ง) | |
| `longitude` | พิกัดลองจิจูด (เส้นแวง) | |
| `quality_flag` | ธงบอกคุณภาพข้อมูล | `G`=Good, `S`=Suspect, `M`=Missing (ใช้กรองข้อมูลขยะ) |
| `basin` | ชื่อลุ่มน้ำประธาน | เช่น ลุ่มน้ำมูล, ลุ่มน้ำชี |
| `sub_basin` | ชื่อลุ่มน้ำสาขา | |
| `tambon`, `amphoe`, `province` | ข้อมูลที่ตั้ง | ระดับ ตำบล, อำเภอ, จังหวัด |
| `data_type` | ประเภทของข้อมูล | ในที่นี้คือ **ฝนรายวัน** |
| **`doy`** | Day of Year | ลำดับวันใน 1 ปี (1-366) ใช้จับคู่ฤดูกาลเพื่อเติมข้อมูล |

---

## 2. `df_model_stations` (Filter List)
> **Description:** บัญชีรายชื่อสถานีเป้าหมาย (Master List) ที่โมเดลต้องการใช้งาน
> **Purpose:** ใช้สำหรับ **"กรอง (Filter)"** เอาเฉพาะสถานีที่จำเป็นออกมาจากข้อมูลดิบ

| Column Name | Description | Note |
| :--- | :--- | :--- |
| **`Node`** | รหัสสถานี | 🔑 ใช้จับคู่กับ `tele_station_oldcode` หรือ `station_code` |
| `Lat` | พิกัดละติจูดที่โมเดลระบุ | |
| `Long` | พิกัดลองจิจูดที่โมเดลระบุ | |

---

## 3. `df_2025` (Operational / Input Data)
> **Description:** ข้อมูลดิบรายวันของปี 2025 (ดึงจาก API/Folder รายเดือน)
> **Purpose:** ข้อมูล Input หลัก ข้อมูลชุดนี้มักจะยังไม่สะอาดและมีคอลัมน์ที่เกิดจากการรวมไฟล์หลายแบบ

| Column Name | Description | Note |
| :--- | :--- | :--- |
| `rainfall_datetime` | วันเวลาที่เกิดฝนตก | ตาม Timestamp ของเซ็นเซอร์ |
| `rainfall_datetime_calc` | วันเวลาที่ระบบคำนวณประมวลผล | |
| **`rainfall_value`** | ค่าปริมาณน้ำฝน (mm) | 🎯 ค่าหลักที่จะนำไปใช้งาน |
| `tele_station_id` | รหัส ID อ้างอิงภายในฐานข้อมูล | มักเป็นตัวเลข Running Number |
| **`tele_station_oldcode`** | รหัสสถานีแบบเก่า | 🚨 **สำคัญมาก** มักจะตรงกับ `Node` ในไฟล์ `df_model_stations` (ใช้ Join ตาราง) |
| `measure_datetime` | วันเวลาที่ทำการตรวจวัดมาตรฐาน | ใช้สำหรับ Group by วันที่ |
| `station_code` | รหัสสถานี | *หมายเหตุ: มีค่า Non-Null น้อย (อาจติดมาจากไฟล์บางส่วน)* |
| `value` | ค่าปริมาณฝน | *หมายเหตุ: คู่กับ `station_code` เป็น format สำรองที่มีข้อมูลน้อย* |

## ขั้นตอนที่ 1. กรองเฉพาะสถานีที่อยู่ใน Station in the model_HII.csv

### คำถามที่ 2. กรองข้อมูลให็เหลือเฉพาะสถานีใน Station in the model_HII.csv และแสดงจำนวนสถานีก่อนและหลังกรอง

In [45]:
# แสดงจำนวนสถานีใน Station in the model_HII.csv

df_model_stations.shape[0]

385

In [50]:
# แสดงจำนวนสถานีทั้งหมด df_2025 1.จำนวนทั้งหมด (ทุดแถวทั้งหมด) 2.total_unique

# 1. จำนวนทั้งหมด (ทุกแถวทั้งหมด)
total_rows_df_2025 = len(df_2025)
print(f"Total number of records (rows) in df_2025: {total_rows_df_2025}")

# 2. total_unique stations
total_unique_stations_df_2025 = df_2025['tele_station_oldcode'].nunique()
print(f"Total number of unique stations in df_2025: {total_unique_stations_df_2025}")

Total number of records (rows) in df_2025: 180700
Total number of unique stations in df_2025: 1514

In [52]:
# กรองข้อมูลโดยเช็คว่า 'tele_station_oldcode' มีอยู่ในรายการของ 'Node' หรือไม่
df_2025_filtered_stations = df_2025[df_2025['tele_station_oldcode'].isin(df_model_stations['Node'])].copy()
df_2025_filtered_stations.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,station_code,value
1,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,265.0,BNLG,2025-07-20,NaN,NaN
5,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,358.0,CHI012,2025-07-20,NaN,NaN
7,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,325.0,BNPI,2025-07-20,NaN,NaN
8,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.0,326.0,PHON,2025-07-20,NaN,NaN
10,2025-07-21 00:00:00+07:00,2025-07-21T07:00:00+07:00,0.2,448.0,PASG,2025-07-20,NaN,NaN

In [53]:
# แสดงจำนวนสถานีทั้งหมด df_2025_filtered_stations 1.จำนวนทั้งหมด (ทุดแถวทั้งหมด) 2.total_unique

# 1. จำนวนทั้งหมด (ทุกแถวทั้งหมด)
total_rows_df_2025_filtered_stations = len(df_2025_filtered_stations)
print(f"Total number of records (rows) in df_2025_filtered_stations: {total_rows_df_2025_filtered_stations}")

# 2. total_unique stations
total_unique_stations_df_2025_filtered_stations = df_2025_filtered_stations['tele_station_oldcode'].nunique()
print(f"Total number of unique stations in df_2025_filtered_stations: {total_unique_stations_df_2025_filtered_stations}")

Total number of records (rows) in df_2025_filtered_stations: 66275
Total number of unique stations in df_2025_filtered_stations: 384

### คำถามที่ 3. ระบุข้อมูลสูญหาย (record ที่หายไป (ไม่ใช่ค่า NULL หรือ NaN)) ของแต่ละสถานี แสดงจำนวนและสัดส่วน

In [60]:
# --- 3.1 เตรียมข้อมูลวันที่ให้เป็น format datetime ---
# แปลง column measure_datetime เป็น datetime object และตัดเอาแค่วันที่ (ตัดเวลาทิ้ง) เพื่อการเปรียบเทียบ
df_2025_filtered_stations['measure_date'] = pd.to_datetime(df_2025_filtered_stations['measure_datetime']).dt.date

# กำหนดช่วงเวลาที่ควรจะมีข้อมูล (ตาม Folder ที่ระบุคือ 2025-07 ถึง 2025-12)
start_date = pd.to_datetime('2025-07-01').date()
end_date = pd.to_datetime('2025-12-31').date()
full_date_range = pd.date_range(start=start_date, end=end_date, freq='D').date

# จำนวนวันที่ควรจะมีทั้งหมด
total_expected_days = len(full_date_range)
print(f"Total expected days (Jul-Dec 2025): {total_expected_days} days")

# --- 3.2 สร้างตารางหลัก (Master Template) ที่มีครบทุกสถานีและทุกวัน ---
unique_stations = df_2025_filtered_stations['tele_station_oldcode'].unique()

# สร้าง MultiIndex ที่เป็นการจับคู่กันระหว่าง ทุกสถานี x ทุกวัน (Cartesian Product)
index = pd.MultiIndex.from_product([unique_stations, full_date_range], names=['tele_station_oldcode', 'measure_date'])
df_full_template = pd.DataFrame(index=index).reset_index()

# --- 3.3 นำข้อมูลจริงมา Merge กับตารางหลัก ---
# ทำ Left Join: ยึดตารางหลักไว้ ถ้าวันไหนในข้อมูลจริงไม่มี ค่า rainfall_value จะกลายเป็น NaN
# ก่อน Merge ต้องจัดการ Duplicate ในข้อมูลจริงก่อน (เผื่อวันหนึ่งมีหลาย record) โดยเลือกค่าใดค่าหนึ่ง หรือค่าเฉลี่ย (ในที่นี้ขอเลือก record แรกที่เจอเพื่อเช็คการมีอยู่)
df_actual_unique = df_2025_filtered_stations.drop_duplicates(subset=['tele_station_oldcode', 'measure_date'])

df_merged = pd.merge(df_full_template,
                     df_actual_unique[['tele_station_oldcode', 'measure_date', 'rainfall_value']],
                     on=['tele_station_oldcode', 'measure_date'],
                     how='left')

# --- 3.4 คำนวณจำนวนและสัดส่วนข้อมูลที่หายไป ---
# สร้างตารางสรุปผล
missing_stats = df_merged.groupby('tele_station_oldcode').apply(
    lambda x: pd.Series({
        'total_expected': len(x),
        'missing_count': x['rainfall_value'].isna().sum(), # นับจำนวนวันที่ไม่มีข้อมูล (NaN หลังจากการ Merge)
        'missing_percent': (x['rainfall_value'].isna().sum() / len(x)) * 100
    })
).reset_index()

# แสดงตัวอย่างผลลัพธ์
print("\n--- Missing Data Statistics per Station ---")
print(missing_stats.head(10))

# แสดงสถิติภาพรวม
print("\n--- Summary Statistics of Missing Data ---")
print(missing_stats[['missing_count', 'missing_percent']].describe())

Total expected days (Jul-Dec 2025): 184 days

--- Missing Data Statistics per Station ---
  tele_station_oldcode  total_expected  missing_count  missing_percent
0                 ACRU           184.0            0.0         0.000000
1                 BBHN           184.0            0.0         0.000000
2                 BBUA           184.0           15.0         8.152174
3                 BCNG           184.0            0.0         0.000000
4                 BDAR           184.0            0.0         0.000000
5                 BDCP           184.0            1.0         0.543478
6                 BDGN           184.0            0.0         0.000000
7                 BDLH           184.0            0.0         0.000000
8                 BDMG           184.0            0.0         0.000000
9                 BGRT           184.0            0.0         0.000000

--- Summary Statistics of Missing Data ---
       missing_count  missing_percent
count     384.000000       384.000000
mean       11.411458         6.201880
std        30.255008        16.442939
min         0.000000         0.000000
25%         0.000000         0.000000
50%         0.000000         0.000000
75%         1.250000         0.679348
max       169.000000        91.847826

/tmp/ipython-input-1543085067.py:33: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  missing_stats = df_merged.groupby('tele_station_oldcode').apply(

## ขั้นตอนที่ 2. ลบสถานีที่มีข้อมูลสูญหาย มากกว่าหรือเท่ากับ 20%

### คำถามที่ 4. คัดสถานีที่มีข้อมูลสูญหาย มากกว่าหรือเท่ากับ 20% ออก แสดงรายชื่อสถานีที่ถูกคัดออกและจำนวนที่เหลือ

In [61]:
# --- 4.1 กำหนดเกณฑ์และแยกกลุ่มสถานี ---
THRESHOLD_PERCENT = 20.0

# หา List สถานีที่ต้อง "คัดออก" (Missing >= 20%)
stations_to_drop = missing_stats[missing_stats['missing_percent'] >= THRESHOLD_PERCENT]
dropped_list = stations_to_drop['tele_station_oldcode'].tolist()

# หา List สถานีที่ "เก็บไว้" (Missing < 20%)
stations_to_keep = missing_stats[missing_stats['missing_percent'] < THRESHOLD_PERCENT]
kept_list = stations_to_keep['tele_station_oldcode'].tolist()

# --- 4.2 กรอง DataFrame หลักให้เหลือเฉพาะสถานีที่เก็บไว้ ---
# เราใช้ df_merged จากขั้นตอนที่ 3 เพราะตารางนี้มี row ของวันที่หายไปเตรียมไว้ให้ (เป็น NaN) พร้อมสำหรับขั้นตอนที่ 5
df_clean_for_impute = df_merged[df_merged['tele_station_oldcode'].isin(kept_list)].copy()

# --- 4.3 แสดงผลลัพธ์ ---
print(f"Criteria: Remove stations with missing data >= {THRESHOLD_PERCENT}%")
print("-" * 60)
print(f"Number of stations DROPPED : {len(dropped_list)}")
print(f"Number of stations REMAINING: {len(kept_list)}")
print("-" * 60)

print("List of dropped stations (Code):")
if len(dropped_list) > 0:
    print(dropped_list)
else:
    print("None (No stations exceeded the missing threshold)")

print("\nShape of data ready for imputation:", df_clean_for_impute.shape)

Criteria: Remove stations with missing data >= 20.0%
------------------------------------------------------------
Number of stations DROPPED : 45
Number of stations REMAINING: 339
------------------------------------------------------------
List of dropped stations (Code):
['BKHN', 'BKK017', 'BLKO', 'BNGR', 'BNLG', 'BPTG', 'BSKJ', 'BSPN', 'CEHM', 'CGKM', 'CHI010', 'CHI013', 'CHNA', 'CPY010', 'CTKN', 'DCCT', 'DGSL', 'KKTO', 'KON005', 'LMSK', 'MEWG', 'MMMO', 'MNRM', 'NAPK', 'NASW', 'NEAK', 'NGCG', 'NGPI', 'NKSG', 'NNPT', 'NPI002', 'PAS008', 'PMPN', 'PRN001', 'PSLT', 'SGKW', 'SKE001', 'SKM004', 'SLA002', 'TPI007', 'TUKW', 'VLGE33', 'WAN005', 'YCUM', 'YOM001']

Shape of data ready for imputation: (62376, 3)

## ขั้นตอนที่ 3. เติมข้อมูลด้วย Median ของ Day of Year จาก historical

คำถามที่ 5. เติมข้อมูลที่หายไปด้วยค่า Median ตาม Day of Year จาก historical แยกตามสถานี ตรวจสอบว่าไม่มี record หายอีก

In [62]:
# --- 5.1 เตรียมข้อมูล Historical (หา Median ตาม Day of Year) ---
# แปลงเป็น datetime (ถ้ายังไม่เป็น)
df_history['measure_datetime'] = pd.to_datetime(df_history['measure_datetime'])

# สร้าง column Day of Year (1-366)
df_history['doy'] = df_history['measure_datetime'].dt.dayofyear

# คำนวณ Median แยกตาม สถานี (station_code) และ วันของปี (doy)
# ใช้ 'data' column ซึ่งคือปริมาณฝนใน df_history
historical_medians = df_history.groupby(['station_code', 'doy'])['data'].median().reset_index()
historical_medians.rename(columns={'data': 'median_val'}, inplace=True)

# --- 5.2 เตรียมข้อมูล 2025 ที่จะเติม (df_clean_for_impute) ---
# แปลง measure_date กลับเป็น datetime เพื่อหา doy
df_clean_for_impute['measure_date'] = pd.to_datetime(df_clean_for_impute['measure_date'])
df_clean_for_impute['doy'] = df_clean_for_impute['measure_date'].dt.dayofyear

# --- 5.3 เติมข้อมูล (Imputation) ---
# Merge ค่า Median เข้ามาในตารางหลัก โดยใช้ station code และ doy เป็น key
# หมายเหตุ: ใน df_history ใช้ 'station_code', ใน df_2025 ใช้ 'tele_station_oldcode'
df_imputed = pd.merge(df_clean_for_impute,
                      historical_medians,
                      left_on=['tele_station_oldcode', 'doy'],
                      right_on=['station_code', 'doy'],
                      how='left')

# สร้าง column ใหม่ 'rainfall_filled'
# ถ้ามีค่าเดิมอยู่แล้วให้ใช้ค่าเดิม, ถ้าเป็น NaN ให้ใช้ค่า median_val ที่ดึงมา
df_imputed['rainfall_filled'] = df_imputed['rainfall_value'].fillna(df_imputed['median_val'])

# --- 5.4 ตรวจสอบผลลัพธ์ (Verification) ---
# นับจำนวนช่องว่างที่ยังเหลืออยู่ (ในกรณีที่ Historical ก็ไม่มีข้อมูลของวันนั้นๆ เลย)
remaining_nans = df_imputed['rainfall_filled'].isna().sum()
total_records = len(df_imputed)

print(f"--- Imputation Result ---")
print(f"Total records processed: {total_records}")
print(f"Missing values BEFORE imputation: {df_clean_for_impute['rainfall_value'].isna().sum()}")
print(f"Missing values AFTER imputation : {remaining_nans}")

if remaining_nans == 0:
    print("\n✅ SUCCESS: No missing records remaining.")
else:
    print(f"\n⚠️ WARNING: There are still {remaining_nans} missing records.")
    print("This happens if the historical data also lacks data for that specific station and day of year.")
    # (Optional) เติมด้วย 0 หรือค่าเฉลี่ยรวมของสถานีนั้นๆ หากจำเป็น
    # df_imputed['rainfall_filled'].fillna(0, inplace=True)

# แสดงตัวอย่างข้อมูลที่ถูกเติม (เลือกดูเฉพาะแถวที่ค่าเดิมเป็น NaN)
print("\nExample of imputed rows:")
print(df_imputed[df_imputed['rainfall_value'].isna()][['tele_station_oldcode', 'measure_date', 'rainfall_filled', 'median_val']].head())

--- Imputation Result ---
Total records processed: 62376
Missing values BEFORE imputation: 541
Missing values AFTER imputation : 0

✅ SUCCESS: No missing records remaining.

Example of imputed rows:
     tele_station_oldcode measure_date  rainfall_filled  median_val
838                PAS001   2025-10-11              0.0         0.0
1288               NKO001   2025-07-01              4.5         4.5
1289               NKO001   2025-07-02              0.2         0.2
1290               NKO001   2025-07-03              0.0         0.0
1291               NKO001   2025-07-04              0.5         0.5

#### 6. อภิปรายว่า เหตุใดใช้ Median แทน Mean

ข้อมูลน้ำฝนมีการกระจายตัวแบบเบ้ขวา (Right-skewed) คือมีวันฝนไม่ตก (0 mm) จำนวนมาก และมีวันฝนตกหนัก (Outliers) จำนวนน้อย

ค่า Mean จะถูกดึงด้วยค่าฝนตกหนัก ทำให้ค่าที่ได้สูงเกินจริงสำหรับวันปกติ

ค่า Median จะระบุค่ากลางที่แท้จริงได้ดีกว่า (Robust to outliers)

## ขั้นตอนที่ 4. รวมปริมาณฝนแต่ละวันเป็นผลรวมรายเดือน

### 7. คำนวณผลรวมปริมาณน้ำฝนรายเดือน จัดรูปแบบให้ตรงกับ output_monthly_rainfall.cs

In [67]:
# Ensure 'measure_date' is datetime type
df_imputed['measure_date'] = pd.to_datetime(df_imputed['measure_date'])

# Extract Year and Month
df_imputed['year'] = df_imputed['measure_date'].dt.year
df_imputed['month'] = df_imputed['measure_date'].dt.month

# Calculate monthly rainfall totals
df_monthly_rainfall = df_imputed.groupby(['tele_station_oldcode', 'year', 'month'])['rainfall_filled'].sum().reset_index()

# Rename the rainfall column for clarity
df_monthly_rainfall.rename(columns={'rainfall_filled': 'total_monthly_rainfall'}, inplace=True)

# Display the results
print("\n--- Monthly Rainfall Totals ---")
print(df_monthly_rainfall.head())

print(f"\nShape of monthly rainfall data: {df_monthly_rainfall.shape}")

--- Monthly Rainfall Totals ---
  tele_station_oldcode  year  month  total_monthly_rainfall
0                 ACRU  2025      7                    83.0
1                 ACRU  2025      8                   164.8
2                 ACRU  2025      9                   248.6
3                 ACRU  2025     10                    48.4
4                 ACRU  2025     11                    52.2

Shape of monthly rainfall data: (2034, 4)

In [68]:
df_monthly_rainfall

     tele_station_oldcode  year  month  total_monthly_rainfall
0                    ACRU  2025      7                    83.0
1                    ACRU  2025      8                   164.8
2                    ACRU  2025      9                   248.6
3                    ACRU  2025     10                    48.4
4                    ACRU  2025     11                    52.2
...                   ...   ...    ...                     ...
2029               YOM012  2025      8                   149.8
2030               YOM012  2025      9                   256.0
2031               YOM012  2025     10                    30.0
2032               YOM012  2025     11                   100.6
2033               YOM012  2025     12                     8.0

[2034 rows x 4 columns]

In [79]:
# 1. เปลี่ยนชื่อคอลัมน์
df_monthly_rainfall.rename(columns={
    'tele_station_oldcode': 'Node',
    'total_monthly_rainfall': 'rain'
}, inplace=True)

# 2. จัดลำดับคอลัมน์ใหม่: Node -> rain -> month -> year
df_monthly_rainfall = df_monthly_rainfall[['Node', 'rain', 'month', 'year']]


# แสดงผลลัพธ์ (ใช้ index=False เพื่อให้เหมือนใน Excel ที่ไม่มีเลขแถวข้างหน้า)
# print(df_monthly_rainfall.to_string(index=False))

        Node   rain  month  year
0       ACRU   83.0      7  2025
1       ACRU  164.8      8  2025
2       ACRU  248.6      9  2025
3       ACRU   48.4     10  2025
4       ACRU   52.2     11  2025
...      ...    ...    ...   ...
2029  YOM012  149.8      8  2025
2030  YOM012  256.0      9  2025
2031  YOM012   30.0     10  2025
2032  YOM012  100.6     11  2025
2033  YOM012    8.0     12  2025

[2034 rows x 4 columns]

In [91]:
# 1. ติดตั้งและ Authentication
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

# เชื่อมต่อกับ Google Sheets
gc = gspread.authorize(creds)

# 2. สร้างไฟล์ Google Sheet ใหม่
sheet_name = 'output_monthly_rainfall_663020620-0'
sh = gc.create(sheet_name)

# 3. เลือก Worksheet แรก
worksheet = sh.get_worksheet(0)

# 4. เขียนข้อมูลลงไป
# แปลง DataFrame เป็น List of Lists
data_to_export = [df_monthly_rainfall.columns.values.tolist()] + df_monthly_rainfall.values.tolist()

# อัปเดตข้อมูลลง Sheet
worksheet.update(range_name='A1', values=data_to_export)

print(f"✅ บันทึกข้อมูลลง Google Sheet เรียบร้อยแล้ว")
print(f"ชื่อไฟล์: {sheet_name}")
print(f"Link: {sh.url}")

✅ บันทึกข้อมูลลง Google Sheet เรียบร้อยแล้ว
ชื่อไฟล์: output_monthly_rainfall_663020620-0
Link: https://docs.google.com/spreadsheets/d/145RE6GgIztv7ZNAeepCdVmkcVpB8Fm1-QFu3tkYm8fs